version: "3.9"

services:
  api:
    # container_name: node_api
    build: .
    # ports:
    #   - 3000:3000

  Nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:3000
